apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
patchesStrategicMerge:
  - ingress.yaml
resources:
  - ../../base
images:
  - name: registry.scg.skku.ac.kr/ourlim-fe
    newTag: '72'
  - name: registry.scg.skku.ac.kr/ourlim-be
    newTag: '72'
