apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ourlim
namePrefix: dev-
patchesStrategicMerge:
- ingress.yaml
resources:
- ../../base
images:
- name: registry.scg.skku.ac.kr/ourlim-be
  newTag: "23"
- name: registry.scg.skku.ac.kr/ourlim-fe
  newTag: "23"
