apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ourlim
namePrefix: prod-
patchesStrategicMerge:
- ingress.yaml
- deployment.yaml
- service.yaml
resources:
- ../../base
- secret.yaml
images:
- name: harbor.k8s.scg.skku.ac.kr/library/ourlim-be
  newTag: "prod1"