apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      containers:
        - image: registry.scg.skku.ac.kr/ourlim-fe
          imagePullPolicy: Always
          name: fe
          ports:
            - containerPort: 3000
        - image: registry.scg.skku.ac.kr/ourlim-be
          imagePullPolicy: Always
          name: be
          ports:
            - containerPort: 8000
